 name: My first workflow
 on: push

 jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:
      - name: Welcome Message
        run: echo "Welcome to gitHub Actions"
      
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la

      - name: Open File
        run: cat README.md
