 name: My first workflow
 on: push

 jobs:
    first_job:
      runs-on: ubuntu-latest
      steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: List Repo files
        run: ls -ltrh

      - name: Execute Shell Script
        run: |
            chmod +x script.sh
            sh script.sh
